= Using IPv6 With Couchbase Server
:page-edition: Enterprise

[abstract]
Couchbase Server supports IP version 6 (IPv6).
You can set up IPv6 on new clusters, or upgrade existing clusters from IPv4 to IPv6.

[#ipv6-overview]
== Overview

By default, new installations of Couchbase Server start up using IPv4.


IPv6 on new clusters::
By default, new installations of Couchbase Server start up using IPv4.
This has the implication of requiring that you convert the first node to use IPv6 before you initialize the cluster.  on a new cluster, each node needs to be converted to IPv6 before you add them 

By default, new installations of Couchbase Server start up using IPv4.
That means when you set up IPv6 on a new cluster, each node needs to be converted to IPv6 before you add them 
To enable IPv6, set-up is required for each platform, as described in the sections below.
Note that the steps for Linux and macOS are to be performed _after_ the basic Couchbase Server installation is complete, and the steps for Windows are integrated into the basic installation procedure itself.

NOTE: In a clustered setup, IPv6 is enabled only when IPv6 is enabled on all of the nodes.

See xref:install-intro.adoc[Installing the Couchbase Server Cluster] for more information about installation procedures.

[#linux-ipv6-setup]
== IPv6 Set-Up for Linux

After the Couchbase Server package has been installed, the `couchbase` service is started by default.
To enable IPv6, proceed as follows:

. Stop the `couchbase-server` service.
. In `/opt/couchbase/etc/couchbase/static_config`, set `ipv6` to `true`.
. Delete `/opt/couchbase/var/lib/couchbase/config/config.dat`.
. Restart the `couchbase-server` service (this starts Couchbase Server in IPv6 mode).
To check, point a supported web browser to  `http://[::1]:8091`, which is the IPv6 address and port number on which Couchbase Server should be running.

[#windows-ipv6-setup]
== IPv6 Set-Up for Windows

IPv6 set-up requirements are incorporated into the InstallShield wizard itself.
During installation of the Couchbase package, a check box is available to enable IPv6 mode.
(Note that after installation, any subsequent mode-change requires re-installation.)

[#macos-ipv6-setup]
== IPv6 Set-Up for macOS

After you install the Couchbase Server application, proceed as follows:

. Ensure that the `couchbase-server` service is stopped.
(Quit the Couchbase Server application if it is running.)
. In `/Applications/Couchbase\ Server.app/Contents/Resources/couchbase-core/etc/couchbase/static_config.in`, set `ipv6` to `true`.
. Delete `~/Library/Application\ Support/Couchbase/var/lib/couchbase/config/config.dat`.
. Restart the `couchbase-server` service (this starts Couchbase Server in IPv6 mode).
To check, point a supported web browser to  `http://[::1]:8091`, which is the IPv6 address and port number on which Couchbase Server should be running.
