= Upgrade to Couchbase Server 6.5
:page-aliases: install:upgrade-strategy-for-features,

This page shows you how to upgrade to the latest 6.5 release using an xref:upgrade.adoc#upgrade-types[online rolling upgrade], incurring little to no downtime.

== Verify Your Upgrade Path

Couchbase Server supports direct upgrades up to one major version ahead.
That means, you can upgrade to version 6.5 from any version in the 5.x or 6.0.x series of releases.

If you're upgrading from a version older than 5.x, you need to upgrade to an intermediate release before you can upgrade to version 6.5.
You can review the supported xref:upgrade.adoc#upgrade-paths[upgrade paths] to better understand your options. 

== Plan Your Upgrade Strategy

Upgrading a Couchbase cluster is accomplished by upgrading each of its constituent nodes to the new version.
The most common way to upgrade a cluster is by performing an xref:upgrade.adoc#upgrade-types[online upgrade].
Only once all of the nodes are running the new version, will the cluster be considered fully upgraded.
Up until that point, if any node in the cluster is running the old version of Couchbase Server, then the entire cluster is considered to be in _mixed mode_.

Even though all nodes in a cluster have Couchbase Server installed on them, each node might only run one or more Couchbase xref:learn:services-and-indexes/services/services.adoc[Services].
Some nodes might run the Data Service, while other nodes might be responsible for Index, Query, etc.
This has two practical implications for upgrade:

=== Ensure Proper Service Coverage

A given Couchbase service must always be running on an active node to avoid disruption and downtime.

When you remove one or more nodes from a cluster (in this case, for the purposes of upgrade), the cluster will take the data and workloads from the removed nodes and transfer them to other active nodes in the cluster on a service-for-service basis.
What this means is that if, for example, you remove a node that is running the Data Service, the cluster will transfer that node's vBuckets and replica vBuckets to other nodes running the Data Service.
Similarly, if you remove a node that is running the Index Service, the cluster will rebuild those indexes on other nodes running the Index Service.

If you don't have any active nodes in the cluster that are running the same services as the nodes you are taking out, then those services will experience downtime until the nodes become active again.
In addition, even if you have multiple active nodes running the same service, they must also have enough spare capacity to take on the data and workloads of the removed nodes, otherwise you may experience disruptions in that service.

=== Prepare for Feature Upgrades

Depending on the size and scope of a release, a new version of Couchbase Server may come with several new features and enhancements.
New features generally appear on a node immediately after it has been upgraded.
For example, if your cluster is operating in mixed mode, with some of
For example, if you log into the Couchbase Web Console on a node that has been upgraded, you may see new features and options available, even though other nodes in the clusteronce you upgrade a node and add it into the cluster, you 

When you upgrade Couchbase Server on a node, all of the services on that node are upgraded as well.

Most new features and 


In most production environments, each workload is isolated to its own set of nodes.
There are special considerations for most online upgrade options in an MDS cluster.
For more information on this, see xref:upgrade-online.adoc[Performing the Rolling Online Upgrade].


During the upgrade, your cluster can have a mix of the new and current versions of the query, index, or data services.

Data Service

You can upgrade the Data service from version 4.0 directly to the latest version 4.1 using any supported upgrade strategy

Index Service

The Index service with global secondary indexes (GSI) does not provide built-in replicas.
Administrators need to create identical indexes on the separate index service nodes to gain high availability.

The Index service also comes with no rebalancing support.
When a node is removed, GSI on that node are also removed and not moved to another node.
The index traffic is automatically moved to another node that contains an identical index so that the application does not experience downtime.
However, when the upgraded Index service node is brought back into the cluster, administrators have to rebuild the indexes on this node again.

When upgrading the Index service, make sure to fulfill these requirements:

* Before you upgrade an index service node, ensure there are identical indexes on other index service nodes for each index on the node being upgraded.
* Upgrade the node with the Index service and add it back to the cluster using one of the recommended techniques (swap rebalance, offline upgrade, and so on).
* Recreate all indexes on the upgraded node.

Query Service

The Query service can be upgraded to a new version by taking the node offline.
However, there are few things to keep in mind:

* Make sure there are no running or executing queries since those will be killed when the node is taken offline.
* To avoid downtime for your application, add a new query service node with the new version and swap the older node out.

== Prepare for Upgrade

Before starting the upgrade, complete the following steps.

. Verify the overall health of the cluster from the Couchbase Web Console.
+
* Under [.ui]*Servers*, ensure that only active nodes are listed, and that they have a green status.
Nodes should not be failed over, marked for addition/removal, or in the process of rebalancing.
If any of the nodes are failed over, offline, or have any other type of unhealthy status, you need to identify the cause and either bring them back online to normal running status, or remove them.
+
* Under [.ui]*Servers > Statistics*, check that resource capacity is adequate enough for your upgrade strategy.
If you're not swapping in any net-new nodes, you need to ensure that you have enough spare capacity to handle nodes coming in and out of the cluster.
* Ensure that buckets and indexes have an adequate number of replicas to ensure that you meet the desired availability levels for your upgrade strategy. 

. Create a xref:backup-restore:backup-restore.adoc[backup] of the cluster.
It's good practice to create a backup before upgrading a cluster.
You can use this backup to restore your cluster to its pre-upgraded state for the purposes of xref:upgrade.adoc#rollback-downgrade[downgrade] or disaster recovery.

. As an extra precautionary measure, you should capture diagnostic information for the cluster by running the xref:cli/cbcollect-info-tool.adoc[`cbcollect_info`] tool.
If you encounter troubles during the upgrade, this diagnostic information can aid in troubleshooting the issue.

== Step 2: Prepare for the Upgrade

Before upgrading your production cluster, be sure to practice and verify the upgrade on a test environment first.
The test environment should match your production environment as closely as possible.

If you can, it is best to upgrade during off hours.
Avoid upgrading during the system’s peak usage times.
Even though rebalances are designed to be a background process, they can sometimes impact performance.


== Performing the Rolling Online Upgrade

[abstract]
A rolling online upgrade is the recommended upgrade process for a Couchbase cluster.

== Swap Rebalance Example

You can perform a swap rebalance to upgrade your Couchbase Server nodes without reducing your cluster performance due to diminished capacity from missing nodes.

You need at least one extra node to perform a swap rebalance.
If you are unable to perform an upgrade via swap rebalance, perform a standard online upgrade instead.

*Without a spare node available*

If you don't have an extra node available, and you have enough cluster capacity to service requests after removing one of the nodes, prepare for swap rebalance by first removing an existing node to serve as the initial swap node:

. Back up the entire cluster.
. Remove one node from the cluster by selecting menu:Manage[Server Nodes, Remove Server] for the node you wish to remove.
. Click [.in]`Rebalance`.
. Proceed with the instructions.

== Swap Rebalance Example with an Extra Node Available

. Install the latest version of Couchbase Server on the extra node that is not yet a part of the cluster.
For instructions see xref:upgrade-individual-nodes.adoc[Performing the Single Node Upgrade].
. Create a backup of your cluster data using the xref:cli:cbbackup-tool.adoc[cbbackup tool].
. Open the Couchbase Web Console on an existing cluster node.
. Select menu:Servers[Active Servers] to view and manage the cluster nodes.
. Click [.ui]*Add Server*.
. In the [.ui]*Add Server* dialog, provide either a hostname or IP address for the new node to be added.
Enter your Couchbase Server administrative credentials in the fields [.ui]*Username* and [.ui]*Password* and select the appropriate service.
. Remove one of your existing old nodes from the cluster.
+
Under menu:Server Nodes[Servers], click [.ui]*Remove* for the node you want to remove to mark it for removal.

. In the [.ui]*Servers* panel, click [.ui]*Rebalance*.
The rebalance process moves data from the existing node to your newly added node.

Repeat these steps for all the remaining old nodes in the cluster.
You can add and remove multiple nodes from a cluster.
However, always add the same number of nodes from the cluster as you remove.

For example, the addition of 4 nodes and the removal of 4 nodes is classed as a swap rebalance, but the addition of 7 nodes and removal of 4 nodes is not.
